"""empty message

Revision ID: ed09681bfc94
Revises: 5aa4d88937bf
Create Date: 2020-11-01 12:17:07.416600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed09681bfc94'
down_revision = '5aa4d88937bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
  
    op.execute('UPDATE todos SET completed = FALSE WHERE completed is NULL;')

    op.alter_column('todos','completed', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
