"""empty message

Revision ID: 21cc9db1b2ee
Revises: 17cb94cb70e0
Create Date: 2020-11-06 04:48:42.378500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cc9db1b2ee'
down_revision = '17cb94cb70e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True, 
               default=False)

    op.alter_column('todos', 'list_id',
                existing_type=sa.INTEGER(),
                nullable=False)          
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True, 
               default=False)
    # ### end Alembic commands ###
